# Generated by Django 5.0.1 on 2024-07-02 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materialflow', '0002_warehousematerial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='warehousematerial',
            options={'ordering': ['id']},
        ),
    ]
