# Generated by Django 5.0.1 on 2024-05-26 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simple_s', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('tag', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_t', models.DateTimeField(auto_now_add=True)),
                ('coords', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CRMSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('works', 'РАБОТЫ'), ('materials', 'МАТЕРИАЛЫ'), ('documents', 'ДОКУМЕНТЫ'), ('logistics', 'ЛОГИСТИКА'), ('finances', 'ФИНАНСЫ')], default='works', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.IntegerField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=64, null=True)),
                ('ticket_subject', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AreaLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('tag', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_t', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.area')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LayerMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('arealayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.arealayer')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_s.material')),
            ],
        ),
        migrations.CreateModel(
            name='LayerWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('arealayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.arealayer')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_s.work')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('tag', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_t', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_s.organization')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='area',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.object'),
        ),
        migrations.CreateModel(
            name='TimeChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('tag', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_t', models.DateTimeField(auto_now_add=True)),
                ('start_t', models.DateTimeField()),
                ('finish_t', models.DateTimeField()),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.arealayer')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
