# Generated by Django 5.0.1 on 2024-05-26 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('tag', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_t', models.DateTimeField(auto_now_add=True)),
                ('corr_n', models.CharField(blank=True, max_length=1024)),
                ('bik', models.CharField(blank=True, max_length=1024)),
                ('addr', models.CharField(blank=True, max_length=2048)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('tag', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_t', models.DateTimeField(auto_now_add=True)),
                ('smth', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('tag', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_t', models.DateTimeField(auto_now_add=True)),
                ('full_title', models.CharField(blank=True, max_length=1024)),
                ('inn', models.CharField(blank=True, max_length=32, null=True)),
                ('ogrn', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('tag', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_t', models.DateTimeField(auto_now_add=True)),
                ('okei', models.CharField(blank=True, default='000', max_length=10, null=True)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('tag', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_t', models.DateTimeField(auto_now_add=True)),
                ('acc_n', models.CharField(blank=True, max_length=1024)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_s.bank')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_s.organization')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('tag', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_t', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('img', models.ImageField(blank=True, null=True, upload_to='services')),
                ('estimate_type', models.CharField(choices=[('FER', 'ФЕР'), ('TER', 'ТЕР'), ('MY', 'СВОЙ')], default='MY', max_length=128)),
                ('estimate_code', models.CharField(blank=True, max_length=128, null=True)),
                ('cat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='simple_s.category')),
                ('unit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='simple_s.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('tag', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_t', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('img', models.ImageField(blank=True, null=True, upload_to='services')),
                ('estimate_type', models.CharField(choices=[('FER', 'ФЕР'), ('TER', 'ТЕР'), ('MY', 'СВОЙ')], default='MY', max_length=128)),
                ('estimate_code', models.CharField(blank=True, max_length=128, null=True)),
                ('cat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='simple_s.category')),
                ('unit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='simple_s.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
