# Generated by Django 5.0.1 on 2024-05-26 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistic', '0001_initial'),
        ('materialflow', '0001_initial'),
        ('simple_s', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialarrival',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='materialflow.warehouse'),
        ),
        migrations.AddField(
            model_name='materialarrival',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='simple_s.organization'),
        ),
        migrations.AddField(
            model_name='materialconsumption',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='simple_s.material'),
        ),
        migrations.AddField(
            model_name='materialconsumption',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workflow.object'),
        ),
        migrations.AddField(
            model_name='materialconsumption',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='materialflow.warehouse'),
        ),
        migrations.AddField(
            model_name='materialrelocation',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='simple_s.material'),
        ),
        migrations.AddField(
            model_name='materialrelocation',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reciever_warehouse', to='materialflow.warehouse'),
        ),
        migrations.AddField(
            model_name='materialrelocation',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender_warehouse', to='materialflow.warehouse'),
        ),
    ]
