# Generated by Django 5.0.1 on 2024-07-02 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0003_alter_materialarrival_options_and_more'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialconsumption',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='consumption_to', to='workflow.arealayer'),
        ),
    ]
